### ISSUE TITLE
Mod request

### ISSUE THREAD

**Issue by Cracko298** [wyndchyme/mc3ds-modern#2]
IronBrutes? No? Okay I'll stop asking lmao.

**Comment by wyndchyme** [comment]
If I was ever going to do a more fantastical modpack, IronBrutes would be first on the list for inclusion. Will put on the todo list for the April 1st, 2025 update ~~(2.9.8, The Homeless Update)~~

**Comment by Cracko298** [comment]
Thank you!!! We should actually add homeless people to mc3ds ngl
